export default {
  feeds: [
    {
      uuid: 12,
      postID: 1122,
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post: "Today I won a car in a competition!",
      time: "5h",
    },

    {
      uuid: 123,
      postID: 112233,
      image: "https://www.venmond.com/demo/vendroid/img/avatar/big.jpg",
      name: "Shirai Subaru",
      post:
        "Today I won a car in a competition! This is a sample of a longer post which has been written by a new person to demonstrate that the size of the feed box should be as long as the text",
      time: "5h",
    },
    {
      uuid: 1232,
      postID: 11223344,
      image: "https://randomuser.me/api/portraits/men/28.jpg",
      name: "Tom Roy",
      post: "This is post by me",
      time: "6h",
    },
    {
      uuid: 112,
      postID: 11223355,
      image: "https://randomuser.me/api/portraits/men/86.jpg",
      name: "Srirag",
      post: "I love Campk12",
      time: "6h",
    },
    {
      uuid: 1256,
      postID: 11223366,
      image: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "Jerry",
      post: "I love Campk12",
      time: "7h",
    },
    {
      uuid: 122,
      postID: 112233777,
      image: "https://randomuser.me/api/portraits/men/22.jpg",
      name: "Sam",
      post: "learn at Campk12",
      time: "8h",
    },
    {
      uuid: 132,
      postID: 11223399,
      image: "https://randomuser.me/api/portraits/men/26.jpg",
      name: "Joe",
      post: "Coding in campk12",
      time: "8h",
    },
    {
      uuid: 100,
      postID: 1000,
      image: "https://randomuser.me/api/portraits/men/30.jpg",
      name: "Raj",
      post: "This is a awesome post",
      time: "10h",
    },
    {
      uuid: 101,
      postID: 1001,
      image: "https://randomuser.me/api/portraits/men/31.jpg",
      name: "Rohit",
      post:
        "This is a awesome post and also this is going to be a very long post. I love campk12. i learn a lot in campk12. Coding in campk12 is fun",
      time: "10h",
    },
    {
      uuid: 102,
      postID: 1002,
      image: "https://randomuser.me/api/portraits/men/32.jpg",
      name: "priyanshu",
      post: "This is another awesome post",
      time: "12h",
    },
    {
      uuid: 103,
      postID: 1003,
      image: "https://randomuser.me/api/portraits/men/33.jpg",
      name: "Sam thomas",
      post: "This is amazing",
      time: "16h",
    },
    {
      uuid: 104,
      postID: 1004,
      image: "https://randomuser.me/api/portraits/men/34.jpg",
      name: "Joseph thomas",
      post: "This is amazing isn't",
      time: "18h",
    },
    {
      uuid: 105,
      postID: 1005,
      image: "https://randomuser.me/api/portraits/women/35.jpg",
      name: "Lilly",
      post: "This is amazing and productive",
      time: "24h",
    },
    {
      uuid: 106,
      postID: 1006,
      image: "https://randomuser.me/api/portraits/men/36.jpg",
      name: "Abhi",
      post: "This is amazing and productive",
      time: "1d",
    },
    {
      uuid: 107,
      postID: 1007,
      image: "https://randomuser.me/api/portraits/men/37.jpg",
      name: "Kiran",
      post: "This is amazing and productive",
      time: "1d",
    },
    {
      uuid: 108,
      postID: 1008,
      image: "https://randomuser.me/api/portraits/women/38.jpg",
      name: "Lil",
      post: "This is amazing and productive",
      time: "1d",
    },
    {
      uuid: 109,
      postID: 1009,
      image: "https://randomuser.me/api/portraits/men/39.jpg",
      name: "Aneesh",
      post: "This is amazing and productive",
      time: "2d",
    },
    {
      uuid: 110,
      postID: 1010,
      image: "https://randomuser.me/api/portraits/men/40.jpg",
      name: "Hardik",
      post: "This is amazing and productive",
      time: "2d",
    },
    {
      uuid: 111,
      postID: 1011,
      image: "https://randomuser.me/api/portraits/men/41.jpg",
      name: "Kiran sr",
      post: "This is amazing and productive",
      time: "2d",
    },
    {
      uuid: 112,
      postID: 1012,
      image: "https://randomuser.me/api/portraits/men/42.jpg",
      name: "Sachin",
      post: "This is amazing and productive",
      time: "2d",
    },
    {
      uuid: 113,
      postID: 1013,
      image: "https://randomuser.me/api/portraits/men/43.jpg",
      name: "Dhan",
      post: "This is amazing and productive",
      time: "2d",
    },

    {
      uuid: 114,
      postID: 1014,
      image: "https://randomuser.me/api/portraits/men/44.jpg",
      name: "Yash",
      post: "This is amazing and productive",
      time: "3d",
    },
    {
      uuid: 115,
      postID: 1015,
      image: "https://randomuser.me/api/portraits/men/45.jpg",
      name: "Das",
      post: "This is amazing and productive",
      time: "3d",
    },
    {
      uuid: 116,
      postID: 1016,
      image: "https://randomuser.me/api/portraits/men/46.jpg",
      name: "Tim",
      post: "This is amazing and productive",
      time: "3d",
    },
    {
      uuid: 117,
      postID: 1017,
      image: "https://randomuser.me/api/portraits/women/47.jpg",
      name: "Shiya",
      post: "This is amazing and productive",
      time: "3d",
    },

    {
      uuid: 118,
      postID: 1018,
      image: "https://randomuser.me/api/portraits/women/48.jpg",
      name: "Priya",
      post: "This is amazing and productive",
      time: "3d",
    },

    {
      uuid: 119,
      postID: 1019,
      image: "https://randomuser.me/api/portraits/men/49.jpg",
      name: "Vishnav",
      post: "This is amazing and productive",
      time: "4d",
    },

    {
      uuid: 120,
      postID: 1020,
      image: "https://randomuser.me/api/portraits/men/50.jpg",
      name: "Virat",
      post: "This is amazing and productive",
      time: "4d",
    },
    {
      uuid: 12,
      postID: 1122900,
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post:
        "I love winning prizes.! it give me more happiness and motivation. Try hard win more!",
      time: "4h",
    },
    {
      uuid: 121,
      postID: 1021,
      image: "https://randomuser.me/api/portraits/men/51.jpg",
      name: "Rohit",
      post: "This is amazing and productive",
      time: "4d",
    },
    {
      uuid: 122,
      postID: 1022,
      image: "https://randomuser.me/api/portraits/women/52.jpg",
      name: "Angeli",
      post: "This is amazing and productive",
      time: "4d",
    },

    {
      uuid: 123,
      postID: 1023,
      image: "https://randomuser.me/api/portraits/women/53.jpg",
      name: "Mega",
      post: "This is amazing and productive",
      time: "4d",
    },

    {
      uuid: 124,
      postID: 1024,
      image: "https://randomuser.me/api/portraits/men/54.jpg",
      name: "Manu",
      post: "This is amazing and productive",
      time: "5d",
    },

    {
      uuid: 121,
      postID: 1221,
      image: "https://randomuser.me/api/portraits/men/51.jpg",
      name: "Rohit",
      post: "Coding is fun, isn't? 😃",
      time: "5d",
    },
    {
      uuid: 1222,
      postID: 1222,
      image: "https://randomuser.me/api/portraits/women/52.jpg",
      name: "Angel",
      post: "This is amazing and productive",
      time: "5d",
    },

    {
      uuid: 223,
      postID: 1223,
      image: "https://randomuser.me/api/portraits/women/53.jpg",
      name: "Megali",
      post: "This is amazing and productive",
      time: "5d",
    },

    {
      uuid: 124,
      postID: 102445,
      image: "https://randomuser.me/api/portraits/men/54.jpg",
      name: "Manu",
      post: "This is amazing and productive",
      time: "6d",
    },

    // 
    // from here

    {
      uuid: 12,
      postID: 2000,
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post: "Here i grow",
      time: "7d",
    },

    {
      uuid: 123,
      postID: 2001,
      image: "https://www.venmond.com/demo/vendroid/img/avatar/big.jpg",
      name: "Shirai Subaru",
      post:
        "This is a sample of a longer post which has been written by a new person to demonstrate that the size of the feed box should be as long as the text",
      time: "7d",
    },
    {
      uuid: 1232,
      postID: 20002,
      image: "https://randomuser.me/api/portraits/men/28.jpg",
      name: "Tom Roy",
      post: "This is post by me",
      time: "7d",
    },
    {
      uuid: 112,
      postID: 20003,
      image: "https://randomuser.me/api/portraits/men/86.jpg",
      name: "Srirag",
      post: "I love Campk12",
      time: "7d",
    },
    {
      uuid: 1256,
      postID: 20004,
      image: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "Jerry",
      post: "I love Campk12",
      time: "8d",
    },
    {
      uuid: 122,
      postID: 20005,
      image: "https://randomuser.me/api/portraits/men/22.jpg",
      name: "Sam",
      post: "learn at Campk12",
      time: "8d",
    },
    {
      uuid: 132,
      postID: 20006,
      image: "https://randomuser.me/api/portraits/men/26.jpg",
      name: "Joe",
      post: "Coding in campk12",
      time: "8d",
    },
    {
      uuid: 100,
      postID: 20007,
      image: "https://randomuser.me/api/portraits/men/30.jpg",
      name: "Raj",
      post: "This is a awesome post",
      time: "8d",
    },
    {
      uuid: 101,
      postID: 20008,
      image: "https://randomuser.me/api/portraits/men/31.jpg",
      name: "Rohit",
      post:
        "I love campk12. i learn a lot in campk12. Coding in campk12 is fun",
      time: "8d",
    },
    {
      uuid: 102,
      postID: 20009,
      image: "https://randomuser.me/api/portraits/men/32.jpg",
      name: "priyanshu",
      post: "This is another awesome post",
      time: "9d",
    },
    {
      uuid: 103,
      postID: 20010,
      image: "https://randomuser.me/api/portraits/men/33.jpg",
      name: "Sam thomas",
      post: "This is amazing",
      time: "9d",
    },
    {
      uuid: 104,
      postID: 20011,
      image: "https://randomuser.me/api/portraits/men/34.jpg",
      name: "Joseph thomas",
      post: "This is amazing isn't",
      time: "9d",
    },
    {
      uuid: 105,
      postID: 20012,
      image: "https://randomuser.me/api/portraits/women/35.jpg",
      name: "Lilly",
      post: "This is amazing and productive",
      time: "9d",
    },
    {
      uuid: 106,
      postID: 20013,
      image: "https://randomuser.me/api/portraits/men/36.jpg",
      name: "Abhi",
      post: "This is amazing and productive",
      time: "10d",
    },
    {
      uuid: 107,
      postID: 20014,
      image: "https://randomuser.me/api/portraits/men/37.jpg",
      name: "Kiran",
      post: "This is amazing and productive",
      time: "10d",
    },
    {
      uuid: 108,
      postID: 20015,
      image: "https://randomuser.me/api/portraits/women/38.jpg",
      name: "Lil",
      post: "This is amazing and productive",
      time: "10d",
    },
    {
      uuid: 109,
      postID: 20016,
      image: "https://randomuser.me/api/portraits/men/39.jpg",
      name: "Aneesh",
      post: "This is amazing and productive",
      time: "10d",
    },
    {
      uuid: 110,
      postID: 20017,
      image: "https://randomuser.me/api/portraits/men/40.jpg",
      name: "Hardik",
      post: "This is amazing and productive",
      time: "11d",
    },
    {
      uuid: 111,
      postID: 20018,
      image: "https://randomuser.me/api/portraits/men/41.jpg",
      name: "Kiran sr",
      post: "This is amazing and productive",
      time: "11d",
    },
    {
      uuid: 112,
      postID: 20019,
      image: "https://randomuser.me/api/portraits/men/42.jpg",
      name: "Sachin",
      post: "This is amazing and productive",
      time: "11d",
    },
    {
      uuid: 113,
      postID: 20020,
      image: "https://randomuser.me/api/portraits/men/43.jpg",
      name: "Dhan",
      post: "This is amazing and productive",
      time: "11d",
    },

    {
      uuid: 114,
      postID: 20021,
      image: "https://randomuser.me/api/portraits/men/44.jpg",
      name: "Yash",
      post: "This is amazing and productive",
      time: "12d",
    },
    {
      uuid: 115,
      postID: 20022,
      image: "https://randomuser.me/api/portraits/men/45.jpg",
      name: "Das",
      post: "This is amazing and productive",
      time: "12d",
    },
    {
      uuid: 116,
      postID: 20023,
      image: "https://randomuser.me/api/portraits/men/46.jpg",
      name: "Tim",
      post: "This is amazing and productive",
      time: "13d",
    },
    {
      uuid: 117,
      postID: 20024,
      image: "https://randomuser.me/api/portraits/women/47.jpg",
      name: "Shiya",
      post: "This is amazing and productive",
      time: "14d",
    },

    {
      uuid: 118,
      postID: 20025,
      image: "https://randomuser.me/api/portraits/women/48.jpg",
      name: "Priya",
      post: "This is amazing and productive",
      time: "15d",
    },

    {
      uuid: 119,
      postID: 20026,
      image: "https://randomuser.me/api/portraits/men/49.jpg",
      name: "Vishnav",
      post: "This is amazing and productive",
      time: "15d",
    },

    {
      uuid: 120,
      postID: 20027,
      image: "https://randomuser.me/api/portraits/men/50.jpg",
      name: "Virat",
      post: "This is amazing and productive",
      time: "16d",
    },
    {
      uuid: 12,
      postID: 20028,
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post:
        "I love winning prizes.! it give me more happiness and motivation. Try hard win more!",
      time: "17h",
    },
    {
      uuid: 121,
      postID: 20029,
      image: "https://randomuser.me/api/portraits/men/51.jpg",
      name: "Rohit",
      post: "This is amazing and productive",
      time: "18d",
    },
    {
      uuid: 122,
      postID: 20030,
      image: "https://randomuser.me/api/portraits/women/52.jpg",
      name: "Angeli",
      post: "This is amazing and productive",
      time: "18d",
    },

    {
      uuid: 123,
      postID: 20031,
      image: "https://randomuser.me/api/portraits/women/53.jpg",
      name: "Mega",
      post: "This is amazing and productive",
      time: "18d",
    },

    {
      uuid: 124,
      postID: 20032,
      image: "https://randomuser.me/api/portraits/men/54.jpg",
      name: "Manu",
      post: "This is amazing and productive",
      time: "19d",
    },

    {
      uuid: 121,
      postID: 20033,
      image: "https://randomuser.me/api/portraits/men/51.jpg",
      name: "Rohit",
      post: "Coding is fun, isn't? 😃",
      time: "20d",
    },
    {
      uuid: 1222,
      postID: 20033,
      image: "https://randomuser.me/api/portraits/women/52.jpg",
      name: "Angel",
      post: "This is amazing and productive",
      time: "21d",
    },

    {
      uuid: 223,
      postID: 20034,
      image: "https://randomuser.me/api/portraits/women/53.jpg",
      name: "Megali",
      post: "This is amazing and productive",
      time: "22d",
    },

    {
      uuid: 124,
      postID: 20035,
      image: "https://randomuser.me/api/portraits/men/54.jpg",
      name: "Manu",
      post: "This is amazing and productive",
      time: "22d",
    },

    
  ],

  user: [
    {
      uuid: 1,
      email: "ajm.shah77@gmail.com",
      password: "123456",
      name: "Ajmal Shah",
    },
    {
      uuid: 2,
      email: "abhishek@gmail.com",
      password: "123456",
      name: "Abhishek",
    },
    {
      uuid: 3,
      email: "Madhav@gmail.com",
      password: "123456",
      name: "Madhav",
    },
    {
      uuid: 4,
      email: "chris@gmail.com",
      password: "123456",
      name: "Chris",
    },
  ],
};
