import { v4 as uuidv4 } from "uuid";
export default {
  feeds: [
    {
      uuid: 5,
      postID: uuidv4(),
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post: "Today I won a car in a competition!",
      time: "5h",
    },

    {
      uuid: 6,
      postID: uuidv4(),
      image: "https://www.venmond.com/demo/vendroid/img/avatar/big.jpg",
      name: "Shirai Subaru",
      post:
        "Today I won a car in a competition! This is a sample of a longer post which has been written by a new person to demonstrate that the size of the feed box should be as long as the text",
      time: "5h",
    },
    {
      uuid: 7,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/1.jpg",
      name: "Tom Roy",
      post: "This is post by me",
      time: "6h",
    },
    {
      uuid: 8,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "Thomas",
      post: "I love coding",
      time: "6h",
    },
    {
      uuid: 9,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/4.jpg",
      name: "Rose",
      post: "Good day guys!",
      time: "6h",
    },
    {
      uuid: 10,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/5.jpg",
      name: "Joe",
      post: "Good Morning",
      time: "7h",
    },
    {
      uuid: 11,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/6.jpg",
      name: "Akash",
      post:
        "Hey this is going to be a very long text to make the feed look more bigger and better 😛",
      time: "7h",
    },
    {
      uuid: 12,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/7.jpg",
      name: "Melvin",
      post: "feed look more better ",
      time: "7h",
    },
    {
      uuid: 13,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/8.jpg",
      name: "Raj",
      post: "Simple day",
      time: "7h",
    },
    {
      uuid: 14,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/9.jpg",
      name: "Stan",
      post: "Coding life ",
      time: "7h",
    },
    {
      uuid: 15,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/10.jpg",
      name: "Smitha",
      post: "Happy today",
      time: "8h",
    },
    {
      uuid: 16,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/11.jpg",
      name: "Latha",
      post: "Happy happy",
      time: "8h",
    },
    {
      uuid: 17,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/12.jpg",
      name: "Madu",
      post: "Enjoying life",
      time: "8h",
    },
    {
      uuid: 5,
      postID: uuidv4(),
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post: "This is testing post done to demonstate the feed",
      time: "8h",
    },

    {
      uuid: 6,
      postID: uuidv4(),
      image: "https://www.venmond.com/demo/vendroid/img/avatar/big.jpg",
      name: "Shirai Subaru",
      post: "This is testing post done to demonstate the feed",
      time: "9h",
    },
    {
      uuid: 7,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/1.jpg",
      name: "Tom Roy",
      post: "This is testing post done to demonstate the feed",
      time: "9h",
    },
    {
      uuid: 8,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "Thomas",
      post: "This is testing post done to demonstate the feed",
      time: "9h",
    },
    {
      uuid: 9,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/4.jpg",
      name: "Rose",
      post: "This is testing post done to demonstate the feed",
      time: "9h",
    },
    {
      uuid: 10,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/5.jpg",
      name: "Joe",
      post: "This is testing post done to demonstate the feed",
      time: "9h",
    },
    {
      uuid: 11,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/6.jpg",
      name: "Akash",
      post: "This is testing post done to demonstate the feed",
      time: "9h",
    },
    {
      uuid: 12,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/7.jpg",
      name: "Melvin",
      post: "This is testing post done to demonstate the feed",
      time: "9h",
    },
    {
      uuid: 13,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/8.jpg",
      name: "Raj",
      post: "This is testing post done to demonstate the feed",
      time: "10h",
    },
    {
      uuid: 14,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/9.jpg",
      name: "Stan",
      post: "This is testing post done to demonstate the feed",
      time: "10h",
    },
    {
      uuid: 15,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/10.jpg",
      name: "Smitha",
      post: "This is testing post done to demonstate the feed",
      time: "10h",
    },
    {
      uuid: 16,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/11.jpg",
      name: "Latha",
      post: "This is testing post done to demonstate the feed",
      time: "10h",
    },
    {
      uuid: 17,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/12.jpg",
      name: "Madu",
      post: "This is testing post done to demonstate the feed",
      time: "10h",
    },
    {
      uuid: 5,
      postID: uuidv4(),
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post: "This is testing post done to demonstate the feed",
      time: "11h",
    },

    {
      uuid: 6,
      postID: uuidv4(),
      image: "https://www.venmond.com/demo/vendroid/img/avatar/big.jpg",
      name: "Shirai Subaru",
      post: "This is testing post done to demonstate the feed",
      time: "11h",
    },
    {
      uuid: 7,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/1.jpg",
      name: "Tom Roy",
      post: "This is testing post done to demonstate the feed",
      time: "11h",
    },
    {
      uuid: 8,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "Thomas",
      post: "This is testing post done to demonstate the feed",
      time: "11h",
    },
    {
      uuid: 9,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/4.jpg",
      name: "Rose",
      post: "This is testing post done to demonstate the feed",
      time: "12h",
    },
    {
      uuid: 10,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/5.jpg",
      name: "Joe",
      post: "This is testing post done to demonstate the feed",
      time: "13h",
    },
    {
      uuid: 11,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/6.jpg",
      name: "Akash",
      post: "This is testing post done to demonstate the feed",
      time: "13h",
    },
    {
      uuid: 12,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/7.jpg",
      name: "Melvin",
      post: "This is testing post done to demonstate the feed",
      time: "13h",
    },
    {
      uuid: 13,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/8.jpg",
      name: "Raj",
      post: "This is testing post done to demonstate the feed",
      time: "14h",
    },
    {
      uuid: 14,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/9.jpg",
      name: "Stan",
      post: "This is testing post done to demonstate the feed",
      time: "15h",
    },
    {
      uuid: 15,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/10.jpg",
      name: "Smitha",
      post: "This is testing post done to demonstate the feed",
      time: "16h",
    },
    {
      uuid: 16,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/11.jpg",
      name: "Latha",
      post: "This is testing post done to demonstate the feed",
      time: "17h",
    },
    {
      uuid: 17,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/12.jpg",
      name: "Madu",
      post: "This is testing post done to demonstate the feed",
      time: "18h",
    },

    {
      uuid: 5,
      postID: uuidv4(),
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post: "This is testing post done to demonstate the feed",
      time: "18h",
    },

    {
      uuid: 6,
      postID: uuidv4(),
      image: "https://www.venmond.com/demo/vendroid/img/avatar/big.jpg",
      name: "Shirai Subaru",
      post: "This is testing post done to demonstate the feed",
      time: "19h",
    },
    {
      uuid: 7,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/1.jpg",
      name: "Tom Roy",
      post: "This is testing post done to demonstate the feed",
      time: "19h",
    },
    {
      uuid: 8,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "Thomas",
      post: "This is testing post done to demonstate the feed",
      time: "19h",
    },
    {
      uuid: 9,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/4.jpg",
      name: "Rose",
      post: "This is testing post done to demonstate the feed",
      time: "19h",
    },
    {
      uuid: 10,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/5.jpg",
      name: "Joe",
      post: "This is testing post done to demonstate the feed",
      time: "19h",
    },
    {
      uuid: 11,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/6.jpg",
      name: "Akash",
      post: "This is testing post done to demonstate the feed",
      time: "19h",
    },
    {
      uuid: 12,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/7.jpg",
      name: "Melvin",
      post: "This is testing post done to demonstate the feed",
      time: "19h",
    },
    {
      uuid: 13,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/8.jpg",
      name: "Raj",
      post: "This is testing post done to demonstate the feed",
      time: "20h",
    },
    {
      uuid: 14,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/9.jpg",
      name: "Stan",
      post: "This is testing post done to demonstate the feed",
      time: "20h",
    },
    {
      uuid: 15,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/10.jpg",
      name: "Smitha",
      post: "This is testing post done to demonstate the feed",
      time: "20h",
    },
    {
      uuid: 16,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/11.jpg",
      name: "Latha",
      post: "This is testing post done to demonstate the feed",
      time: "20h",
    },
    {
      uuid: 17,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/12.jpg",
      name: "Madu",
      post: "This is testing post done to demonstate the feed",
      time: "20h",
    },

    {
      uuid: 5,
      postID: uuidv4(),
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post: "This is testing post done to demonstate the feed",
      time: "1d",
    },

    {
      uuid: 6,
      postID: uuidv4(),
      image: "https://www.venmond.com/demo/vendroid/img/avatar/big.jpg",
      name: "Shirai Subaru",
      post: "This is testing post done to demonstate the feed",
      time: "1d",
    },
    {
      uuid: 7,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/1.jpg",
      name: "Tom Roy",
      post: "This is testing post done to demonstate the feed",
      time: "1d",
    },
    {
      uuid: 8,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "Thomas",
      post: "This is testing post done to demonstate the feed",
      time: "1d",
    },
    {
      uuid: 9,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/4.jpg",
      name: "Rose",
      post: "This is testing post done to demonstate the feed",
      time: "1d",
    },
    {
      uuid: 10,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/5.jpg",
      name: "Joe",
      post: "This is testing post done to demonstate the feed",
      time: "1d",
    },
    {
      uuid: 11,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/6.jpg",
      name: "Akash",
      post: "This is testing post done to demonstate the feed",
      time: "1d",
    },
    {
      uuid: 12,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/7.jpg",
      name: "Melvin",
      post: "This is testing post done to demonstate the feed",
      time: "2d",
    },
    {
      uuid: 13,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/8.jpg",
      name: "Raj",
      post: "This is testing post done to demonstate the feed",
      time: "2d",
    },
    {
      uuid: 14,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/9.jpg",
      name: "Stan",
      post: "This is testing post done to demonstate the feed",
      time: "2d",
    },
    {
      uuid: 15,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/10.jpg",
      name: "Smitha",
      post: "This is testing post done to demonstate the feed",
      time: "2d",
    },
    {
      uuid: 16,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/11.jpg",
      name: "Latha",
      post: "This is testing post done to demonstate the feed",
      time: "2d",
    },
    {
      uuid: 17,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/12.jpg",
      name: "Madu",
      post: "This is testing post done to demonstate the feed",
      time: "2d",
    },
    // data model
    {
      uuid: 5,
      postID: uuidv4(),
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },

    {
      uuid: 6,
      postID: uuidv4(),
      image: "https://www.venmond.com/demo/vendroid/img/avatar/big.jpg",
      name: "Shirai Subaru",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    {
      uuid: 7,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/1.jpg",
      name: "Tom Roy",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    {
      uuid: 8,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "Thomas",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    {
      uuid: 9,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/4.jpg",
      name: "Rose",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    {
      uuid: 10,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/5.jpg",
      name: "Joe",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    {
      uuid: 11,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/6.jpg",
      name: "Akash",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    {
      uuid: 12,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/7.jpg",
      name: "Melvin",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    {
      uuid: 13,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/8.jpg",
      name: "Raj",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    {
      uuid: 14,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/9.jpg",
      name: "Stan",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    {
      uuid: 15,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/10.jpg",
      name: "Smitha",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    {
      uuid: 16,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/11.jpg",
      name: "Latha",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    {
      uuid: 17,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/12.jpg",
      name: "Madu",
      post: "This is testing post done to demonstate the feed",
      time: "3d",
    },
    // data model
    {
      uuid: 5,
      postID: uuidv4(),
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post: "This is testing post done to demonstate the feed",
      time: "4d",
    },

    {
      uuid: 6,
      postID: uuidv4(),
      image: "https://www.venmond.com/demo/vendroid/img/avatar/big.jpg",
      name: "Shirai Subaru",
      post: "This is testing post done to demonstate the feed",
      time: "4d",
    },
    {
      uuid: 7,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/1.jpg",
      name: "Tom Roy",
      post: "This is testing post done to demonstate the feed",
      time: "4d",
    },
    {
      uuid: 8,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "Thomas",
      post: "This is testing post done to demonstate the feed",
      time: "4d",
    },
    {
      uuid: 9,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/4.jpg",
      name: "Rose",
      post: "This is testing post done to demonstate the feed",
      time: "4d",
    },
    {
      uuid: 10,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/5.jpg",
      name: "Joe",
      post: "This is testing post done to demonstate the feed",
      time: "5d",
    },
    {
      uuid: 11,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/6.jpg",
      name: "Akash",
      post: "This is testing post done to demonstate the feed",
      time: "5d",
    },
    {
      uuid: 12,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/7.jpg",
      name: "Melvin",
      post: "This is testing post done to demonstate the feed",
      time: "5d",
    },
    {
      uuid: 13,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/8.jpg",
      name: "Raj",
      post: "This is testing post done to demonstate the feed",
      time: "5d",
    },
    {
      uuid: 14,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/9.jpg",
      name: "Stan",
      post: "This is testing post done to demonstate the feed",
      time: "5d",
    },
    {
      uuid: 15,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/10.jpg",
      name: "Smitha",
      post: "This is testing post done to demonstate the feed",
      time: "5d",
    },
    {
      uuid: 16,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/11.jpg",
      name: "Latha",
      post: "This is testing post done to demonstate the feed",
      time: "5d",
    },
    {
      uuid: 17,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/12.jpg",
      name: "Madu",
      post: "This is testing post done to demonstate the feed",
      time: "5d",
    },
     // data model
     {
      uuid: 5,
      postID: uuidv4(),
      image:
        "https://images.unsplash.com/photo-1602030028438-4cf153cbae9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80",
      name: "Nikhil Yadav",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },

    {
      uuid: 6,
      postID: uuidv4(),
      image: "https://www.venmond.com/demo/vendroid/img/avatar/big.jpg",
      name: "Shirai Subaru",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
    {
      uuid: 7,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/1.jpg",
      name: "Tom Roy",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
    {
      uuid: 8,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/2.jpg",
      name: "Thomas",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
    {
      uuid: 9,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/4.jpg",
      name: "Rose",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
    {
      uuid: 10,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/5.jpg",
      name: "Joe",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
    {
      uuid: 11,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/6.jpg",
      name: "Akash",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
    {
      uuid: 12,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/7.jpg",
      name: "Melvin",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
    {
      uuid: 13,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/8.jpg",
      name: "Raj",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
    {
      uuid: 14,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/9.jpg",
      name: "Stan",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
    {
      uuid: 15,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/10.jpg",
      name: "Smitha",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
    {
      uuid: 16,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/women/11.jpg",
      name: "Latha",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
    {
      uuid: 17,
      postID: uuidv4(),
      image: "https://randomuser.me/api/portraits/men/12.jpg",
      name: "Madu",
      post: "This is testing post done to demonstate the feed",
      time: "6d",
    },
  ],

  user: [
    {
      uuid: 1,
      email: "ajm.shah77@gmail.com",
      password: "123456",
      name: "Ajmal Shah",
    },
    {
      uuid: 2,
      email: "abhishek@gmail.com",
      password: "123456",
      name: "Abhishek",
    },
    {
      uuid: 3,
      email: "Madhav@gmail.com",
      password: "123456",
      name: "Madhav",
    },
    {
      uuid: 4,
      email: "chris@gmail.com",
      password: "123456",
      name: "Chris",
    },
  ],
};
